/*
Generated by ChatGPT:

This is a JavaScript file that defines the "App" component of a React application.
It imports modules from the "react-router-dom" library to handle client-side routing and rendering of different components based on the URL path.
The component renders a "<HashRouter>" component, which enables hash-based routing in the application. 
Inside this component, there is a "<Routes>" component that defines all the possible routes that the user can navigate to.

Each route is defined using the "<Route>" component with a "path" attribute and an "element" attribute that specifies the component to be rendered when the user navigates to that path. 
There are several other imported components, such as "Home", "Profile", "MyProfile", "NoMatch", "LoginCard", "RegistrationTab", "Setting", "ToastContainer", "SideBarContainer", "AdminTable", "Follow", and "ForgotPassword", which likely define different pages or functionalities of the application.

Finally, the "App" component is exported as the default export of the module so that it can be imported and used in other parts of the application.
*/

//Commands regarding the terminal:
//First terminal
//cd frontend
//npm install
//npm start

//Second terminal
//npm run build
//serve -s build
//- Network:  http://192.168.8.2:3000

import React from "react";
import "./App.css";
import {
  BrowserRouter,
  Routes,
  Route,
  Router,
  HashRouter,
} from "react-router-dom";
import Home from "./Home";
import Profile from "./Profile";
import MyProfile from "./MyProfile";
import NoMatch from "./NoMatch";
import LoginCard from "./login/LoginCard";
import RegistrationTab from "./login/RegistrationTab";
import Setting from "./Setting";
import { ToastContainer } from "react-toastify";
import SideBarContainer from "./sidebar/SideBarContainer";
import AdminTable from "./AdminTable";
import Follow from "./Follow";
import ForgotPassword from "./login/ForgotPassword";

function App() {
  return (
    <HashRouter>
      <ToastContainer />
      <Routes>
        <Route path="/" element={<LoginCard />} />
        <Route path="/home" element={<Home />} />
        <Route path="/register" element={<RegistrationTab />} />
        <Route path="/forget_password" element={<ForgotPassword />} />
        <Route path="/profile" element={<MyProfile />} />
        <Route path="/:userid" element={<Profile />} />
        <Route path="/follow" element={<Follow />} />
        <Route path="/setting" element={<Setting />} />
        <Route path="/admin" element={<AdminTable />} />
        <Route path="*" element={<NoMatch />} />
      </Routes>
    </HashRouter>
  );
}

export default App;
